version: '3.1'

services:
  postgres:
    image: postgres:latest
    container_name: db_postgres_hestia_mobile
    environment:
      POSTGRES_DB: postgres  
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5432:5432" 
